### ISSUE TITLE
Reduce code duplication of adding new networks/bridges

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1146]
Currently we support ~6 networks / ~3 bridges and the amount of code required to support new pairs seems quite high (see https://github.com/paritytech/parity-bridges-common/pull/1122/files#).

The code looks very similar though, but it uses completely different types without a common trait implementation so it's not easy to extract the generic part. What we would need is "generic modules", but these are obviously not available.

However it's possible to reduce some of the boilerplate by using macros (see `select_bridge!` in CLI as an example). It would be cool to take a look at what trade-off are we talking about: macro complexity vs code reduction.

**Comment by svyatonik** [comment]
There aren't many lines required now. Bridge declaration is now actually looks like declaration (e.g. [here](https://github.com/paritytech/parity-bridges-common/blob/b56f6a87de6479ae6ce16dca5fddf4c491a33f5a/relays/bin-substrate/src/chains/kusama_headers_to_polkadot.rs) and [here](https://github.com/paritytech/parity-bridges-common/blob/b56f6a87de6479ae6ce16dca5fddf4c491a33f5a/relays/bin-substrate/src/chains/kusama_messages_to_polkadot.rs)). Call builders is the most annoying thing in current declarations - it shall be fixed with #446 . So I'm closing this issue now
