### ISSUE TITLE
Prevent concurrent finality/messages submissions via `SignedExtension`

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1162]
Related: #983 

Currently we allow anyone to submit a finality proof or deliver valid messages. This is nice, but in real world in case many relayers (per-lane) are present they are going to simply compete with each other to submit the information.

The winning relayer is going to be rewarded (also the submission costs might be returned `PaysFee::No` (see #983)), but loosing relayers are going to pay costs for failed dispatch.

To alleviate the issue we can easily prevent failing transactions from being included by adding another `SignedExtension` which would invalidate such submission transactions that are known to fail. We have to be careful to avoid too many storage reads (to prevent block authors DoS via validity checking), but overall it seems it should be possible.

**Comment by svyatonik** [comment]
Imo we shall only enable this extension on dedicated bridges parachain. But since our parachain bridge is currently on hold, I'm going to try this extension on Millau and run several concurrent relayers to see it in action.

**Comment by EmmanuellNorbertTulbure** [comment]
@svyatonik Do we have this already or something that still needs to be done?

**Comment by svyatonik** [comment]
> Imo we shall only enable this extension on dedicated bridges parachain. But since our parachain bridge is currently on hold, I'm going to try this extension on Millau and run several concurrent relayers to see it in action.

Yes, it needs to be ported to Rococo/Wococo bridge (and to P/K later) + audited

**Comment by bkontur** [comment]
@svyatonik 
I have TODO for `generate_bridge_reject_obsolete_headers_and_messages`,
so this issue is about it?

**Comment by svyatonik** [comment]
Yes. I believe I wanted to add it myself, but there's a problem since it is in `brtidge-runtime-common` and back then you've been avoiding this crate because it had XCMv3 dependency. So yes - it still needs to be added to R<>W, but I haven't had a chance to look at its state today :)

We'll also have another extension related to fee payments (#1657).

**Comment by bkontur** [comment]
actually, some time ago, I was updating to xcmv3 with (pub reexports HaulBlob,..), so I am using this `bridge-runtime-common` because of verify proof stuff + plus lots of other stuff,

I would like to also later port back to bridges repo (maybe to `bridge-runtime-common`) some stuff from here: https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_common_config.rs#L53-L55  (but I am still waiting for few small comments to be fixed in XCMv3)

**Comment by serban300** [comment]
Posted https://github.com/paritytech/cumulus/pull/1972 which adds the signed extensions to the Rococo <> Wococo bridge hubs

**Comment by bkontur** [comment]
@svyatonik @serban300 
Slava, Serban added that `generate_bridge_reject_obsolete_headers_and_messages` to BridgeHub runtimes,
do we need to do anything more here?

**Comment by svyatonik** [comment]
Let's close it, thank you all for the help!
