### ISSUE TITLE
Is there a better way to calculate callback weight?

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/parity-bridges-common#1201]
The message pallet has two callbacks `OnMessageAccepted` and `OnDeliveryConfirmed`. Each callback's pre-dispatch weight
calculated in `weights_ext.rs` and restrict with `single_message_callback_overhead`.

```rs
fn single_message_callback_overhead(db_weight: RuntimeDbWeight) -> Weight {
	db_weight.reads_writes(1, 1)
}
```
https://github.com/paritytech/parity-bridges-common/blob/master/modules/messages/src/lib.rs#L611-L623

However, the callback sometimes wants to do things that need more weight than 1 dB read and 1 dB write. Although, https://github.com/paritytech/parity-bridges-common/blob/master/modules/messages/src/lib.rs#L611-L622  It won't cause a panic if ignore the weight limit. It's would be much better if there is a better way.

An example in our chain is:

```rs
pub struct FeeMarketMessageConfirmedHandler<T>(PhantomData<T>);

impl<T: Config> OnDeliveryConfirmed for FeeMarketMessageConfirmedHandler<T> {
	fn on_messages_delivered(lane: &LaneId, delivered_messages: &DeliveredMessages) -> Weight {
		let now = frame_system::Pallet::<T>::block_number();
		for message_nonce in delivered_messages.begin..=delivered_messages.end {
			if let Some(order) = <Orders<T>>::get((lane, message_nonce)) {
                               // reads + 1
				if !order.is_confirmed() {
					<Orders<T>>::mutate((lane, message_nonce), |order| match order {
						Some(order) => order.set_confirm_time(Some(now)),
						None => {}
					});
					<ConfirmedMessagesThisBlock<T>>::append((lane, message_nonce));
                                        // writes + 2
				}
			}
		}

		<T as frame_system::Config>::DbWeight::get().reads_writes(1, 1)
	}
}
```

**Comment by svyatonik** [comment]
There are three options:
1) change your code so that it fits `reads_writes(1, 1)`;
2) change your code to do all extra actions to `on_initialize` of the next block;
3) you may implement what has been suggested [here](https://github.com/paritytech/parity-bridges-common/pull/1134#issuecomment-918877463) and [here](https://github.com/paritytech/parity-bridges-common/pull/1134#discussion_r708243953) :) Then you may configure your chains to have larger reserve for these callbacks.
