### ISSUE TITLE
Deploy Rococo<>Wococo relayers

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1214]
Make sure that Rococo<>Wococo relayers are running (get in touch with @paritytech/devops team). We were previously running only header relayers, but now we should run complex relayers and also make sure to collect metrics.

**Comment by svyatonik** [comment]
Relay is deployed and running. Next steps are:
1) change transactions mortality;
2) (ideally, but not realistically) run conversion rate updater. This is unlikely to happen, because Wococo/Rococo runtime integration now has no concept of conversion rates and probably we'll keep this;
3) (will need Rococo and Wococo runtime upgrade) serve lane `0x00000001`. This lane will have the same set of filters as Polkadot and Kusama.

Once this is done, we may close the issue

**Comment by svyatonik** [comment]
Done
