### ISSUE TITLE
Reenable BEEFY on Rialto

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1286]
BEEFY has been disabled in #1273 (I was thinking that [`enable_beefy`](https://github.com/paritytech/parity-bridges-common/pull/1273/files#diff-6de790c55651187946779da234f79beb56350de819abf5c976a98a1564552e91R191) is enough, but apparently it isn't). I'll disable alerts in #1285, so they also need to be reenabled after BEEFY is fixed

**Comment by acatangiu** [comment]
I think we can change the polkadot service file to use a deny-list of chain-spec-names instead of using an allow-list as it is right now.
That way we can explicitly keep it disabled on Polkadot, Kusama, Westend, while any other chain reusing the polkadot service file can choose for themselves whether to enable BEEFY using the `enable_beefy` flag.

**Comment by svyatonik** [comment]
closed in #1385
