### ISSUE TITLE
Move bridge subtree from polkadot repo to cumulus repo?

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1395]
Since (1) we're aiming for parachain<>parachain bridge now and (2) common good parachains (statemin?) are hosted in the cumulus repo, it makes sense to move bridges subtree from polkadot repo to cumulus repo. This, however, needs to be discussed with other teams.

**Comment by bkontur** [comment]
subtree is ready:
https://github.com/paritytech/cumulus/tree/bko-bridge-rococo-wococo/parachains/runtimes/bridge-hubs#git-subtree-bridges

but actually `master` is not used, `bko-bridge-ro-wo` branch is used for subtree (once merged to Bridge's master, we can update)

**Comment by svyatonik** [comment]
> subtree is ready: https://github.com/paritytech/cumulus/tree/bko-bridge-rococo-wococo/parachains/runtimes/bridge-hubs#git-subtree-bridges
> 
> but actually `master` is not used, `bko-bridge-ro-wo` branch is used for subtree (once merged to Bridge's master, we can update)

Perfect, thank you! Do you mind opening a PR for adding this subtree to the cumulus? Otherwise the resulting PR (which would contain both subtree and parachains) may grow too large. Or do you think it is best to do that at once or after XCM v3 is merged?

**Comment by bkontur** [comment]
well, I would like to open PRs to Cumulus, once we will be up-to-date as much as possible with (polkadot/substrate) and/or it works on live Rococo/Wococo, there is also some cleaning in BridgeHub runtimes vs Bridges cfg and so on.

afaik, for Rococo/Wococo use case, we dont need to merge anyting to Cumulus, because we can deploy to live Rococo/Wococo from cumulus branch (after we add CI stuff to build runtimes in Cumulus https://github.com/paritytech/devops/issues/1934)

**Comment by bkontur** [comment]
dispuste about subtree
https://github.com/paritytech/polkadot/pull/2515

**Comment by EmmanuellNorbertTulbure** [comment]
Done
