### ISSUE TITLE
Macro for auto-generating bridge runtime APIs declarations

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1431]
Right now chain-specific primitives crates (`primitives/chain-kusama`, `primitives/chain-millau`, ...) mostly consist of 3 sections:
1) chain-specific types and numeric constants;
2) declaration of chain-specific bridge runtime APIs (`KusamaFinalityApi`, `ToKusamaOutboundLaneApi`, `FromKusamaInboundLaneApi`, ...);
3) constants that are stringified names of runtime API methods (`TO_KUSAMA_ESTIMATE_MESSAGE_FEE_METHOD`, `TO_KUSAMA_MESSAGE_DETAILS_METHOD`, `FROM_KUSAMA_MESSAGE_DETAILS_METHOD`, ...).

There must be a way to write something like `declare_bridge_finality_api` and `declare_bridge_messages_api` that will generate all the stuff from (2) and (3) above.

I've tried it long time ago, but the problem was that I was unable to call `decl_runtime_apis` macro from my macro back then. Probably there's a way to do that? Or something has changed.

**Comment by serban300** [comment]
We have implemented a macro that declares all the runtime APIs at once. It would be nice to split it in 2 however, 1 macro for generating the finality API and 1 for generating the messages API, however this is not trivial because `decl_runtime_apis` can't be used twice in a module. 

I will try to do this in a future PR.

**Comment by serban300** [comment]
I couldn't find a solution so far, not even with procedural macros. I might be missing things, but even if it were possible, I think it would be complicated.

From what I understand so far the problem is that `decl_runtime_apis` does:
```
mod sp_api_hidden_includes_DECL_RUNTIME_APIS {
    pub extern crate sp_api as sp_api;
}
```
at the beginning and if we want to call it twice we get an error related to redefining `sp_api_hidden_includes_DECL_RUNTIME_APIS`: `error[E0428]: the name `sp_api_hidden_includes_DECL_RUNTIME_APIS` is defined multiple times`

Maybe we could modify `decl_runtime_apis` somehow. I'm looking into this option.

**Comment by svyatonik** [comment]
Can we probably make something like that:
```rust
pub use finality_api::<everything-except-conflicting-items>;
pub use messages_api::<everything-except-conflicting-items>;

mod finality_api {
  sp_api::decl_runtime_apis! {
   // finality api trait
 }
}

mod messages_api {
  sp_api::decl_runtime_apis! {
    // messages api trait
}
}
```

It looks like a hack, but still a solution :)

**Comment by serban300** [comment]
> Can we probably make something like that:
> 
> ```rust
> pub use finality_api::<everything-except-conflicting-items>;
> pub use messages_api::<everything-except-conflicting-items>;
> 
> mod finality_api {
>   sp_api::decl_runtime_apis! {
>    // finality api trait
>  }
> }
> 
> mod messages_api {
>   sp_api::decl_runtime_apis! {
>     // messages api trait
> }
> }
> ```
> 
> It looks like a hack, but still a solution :)

Nice idea ! I think this might work. I'll try it.

**Comment by serban300** [comment]
Yes. Seems to work. Thanks ! I'll post a PR shortly.
