### ISSUE TITLE
Change `To*InboundLaneApi::message_details` to accept single messages

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#1538]
Follow-up on: #1430

See: https://github.com/paritytech/parity-bridges-common/pull/1430#discussion_r938683806

`To*InboundLaneApi::message_details` receives multiple messages + payloads. If there are a lot of large messages WASM may oom. So it would be safer to change it to process single messages only

**Comment by svyatonik** [comment]
Just a couple of alternative impls:
1) do not change the runtime API, but use loop in the relayer instead;
2) every chain has maximal size of incoming transactions and we may call any API and pass <= size of this data (I mean messages here). So we may split all messages in some chunks, where every chink is <= `MAX_TRANSACTION_SIZE` and call existing runtime API safely.

The original solution is also valid ofc

**Comment by serban300** [comment]
@svyatonik Thank you for the suggestions ! Sorry, a couple more questions:
1. If `message_details()` keeps accepting a `Vec` of messages seems that we may accidentally trigger an oom or an error at runtime if the caller is not careful. If we decide to do this, would it be possible and would it make sense to mark `message_details()` as `unsafe` ? Does the `construct_runtime!` macro support this ?
2. How can we get the `MAX_TRANSACTION_SIZE` ?
3. How big is the overhead of a runtime call ? I'm trying to understand what would be the impact of calling `message_details()` for each message. And how many messages could we have at most in a batch ?

**Comment by svyatonik** [comment]
1. If caller is not careful enough, we don't care. The worst thing that can happen is that he'll get an error instead of actual result. Do you mean rust `unsafe` or some other kind of unsafe? Imo nothing is required here. E.g. we have execute block runtime API and it isn't marked unsafe
2. There's `fn max_extrinsic_size()` of the `bp_runtime::Chain` trait
3. For our case (relayer) it is the cost of: sending WS package, handling it by the node (i.e. reading header), then preparing a runtime environment (inserting some keys to the runtime storage overlay), actually executing WASM code and sending response back to the relayer. I would say it may be quite expensive if messages are super light, but probably it'll be enough for us. Relayer is not the app that needs to be super-optimized for performance, but sometimes low performance may cause issues - i.e. if we miss several blocks and state changes while preparing our own transaction. But as I said - initially one-by-one should be enough

**Comment by serban300** [comment]
Ok, thanks for the answears.

> Do you mean rust unsafe or some other kind of unsafe?

Yes, I mean rust `unsafe`.

> Relayer is not the app that needs to be super-optimized for performance, but sometimes low performance may cause issues - i.e. if we miss several blocks and state changes while preparing our own transaction. But as I said - initially one-by-one should be enough

Ok, I see. Than I'll implement one-by-one first and then see if I can improve it to batching without adding to much complexity.
