### ISSUE TITLE
Benchmarks for bridges repo

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#1588]
1. CI - do we need to add something for bridges CI?
2. do we really need `#[cfg(feature = "runtime-benchmarks")]` for `rialto-parachain` / `rialto-runtime` / `millau-runtime`, if so, then fix all modules, if not just remove
 
3. we will probably need benchmarks at least for bridges pallets (`modules`), which will be used in Cumulus bridge hubm, to calculate weigths

check also: https://github.com/paritytech/parity-bridges-common/issues/587

**Comment by svyatonik** [comment]
1. I believe we had an issue/idea to run benchmarks nightly/on-demand. Running it for every PR is costly
2. All runtimes have that - iiuc to avoid linking benchmarks code into release runtime (which makes them heavier => more expensive). For us it is easier to also support that to make copy-paste easier
3. We have benchmarks for all pallets, why I've asked to file this issue is because I was not sure if they're in a working state after #1587 - I'll check that, fix-if-required + close this issue

**Comment by svyatonik** [comment]
Ok, that's my fault - I forgot that we are only running benchmarks for Millau now. Yeah - I agree that we don't need to run it for `RialtoParachain`, so this `todo!()` doesn't affect us, sorry for the noise!
