### ISSUE TITLE
Add the `BridgeRejectObsoleteHeadersAndMessages` `SignedExtra` for BridgeHubRococo/Wococo

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#1748]
We added the bridge_reject_obsolete_headers_and_messages extension to BridgeHubRococo/BridgeHubWococo, but in the relayer we use [this](https://github.com/paritytech/parity-bridges-common/blob/e575269e5f42624ea2e144974933d0dcc2a7eb05/primitives/polkadot-core/src/lib.rs#L205) which doesn't include it. 

We should add the `BridgeRejectObsoleteHeadersAndMessages` `SignedExtra` for BridgeHubRococo/Wococo

**Comment by svyatonik** [comment]
Just my small comment - since `AdditionalSigned` is `()` for the `BridgeRejectObsoleteHeadersAndMessages`, we don't necessary need to add it to the `SignedExtra`, but still it'd be good to have it there just for clarity. But we may use some stub instead of it (i.e. `struct DummySignedExtra; impl SignedExtension for DummySignedExtra { type AdditionalSigned = (); ... }`) to avoid using complex structures there.
