### ISSUE TITLE
Ensure that we may remove extra folders from bridges subtree in Cumulus

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1774]
We may want to remove unneeded folders from the bridges subtree in Cumulus. We only need pallets, their primitives and `runtime-common`. But e.g. `runtime-common` has references to our testnets, so we can't simply remove testnet runtimes.

We need fix it (remove backreferences) and prepare some script that we may use when updating our subtree in Cumulus that will only leave required folders.

**Comment by bkontur** [comment]
I started with this: https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/scripts/bridges_update_subtree.sh

**Comment by svyatonik** [comment]
Closed #1832: `./bridges/scripts/verify-pallets-build.sh --no-revert` && then `git commit -a -m "Remove extra folders"`.

**Comment by bkontur** [comment]
`verify-pallets-build.sh` is included in cumulus update subtree notes/process:
https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/scripts/bridges_update_subtree.sh#L48
https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/README.md#how-to-update-bridges-subtree

I was able to create subtree update with:
```
./scripts/bridges_update_subtree.sh fetch
./scripts/bridges_update_subtree.sh patch (runs `verify-pallets-build.sh`)
./scripts/bridges_update_subtree.sh merge

+ some manual conflict resolution
```

but it is not that straight because `git subtree pull` creates conflicts with previously deleted files, so `./scripts/bridges_update_subtree.sh merge` just deletes them and simplify conflict resolutions, 
but at the end of merge process `./scripts/bridges_update_subtree.sh patch` have to work and it does, so cool :)

anyway, merge conflicts will just depend on subtree diff

**Comment by bkontur** [comment]
@svyatonik 
wdyt about runnning `partial-repo-build-test` on all PRs?

I am just thinking, we should be able to release subtree whenever, so maybe this check should run on all PRs, ideally, it should run, if PR touches relevant files, but that is very very nice to have :)

or is there any way how to trigger `partial-repo-build-test` step manually in CI?
