### ISSUE TITLE
3 years and 9 months spent on building one bridge

### ISSUE THREAD

**Issue by GopherJ** [paritytech/parity-bridges-common#2540]
https://github.com/paritytech/parity-bridges-common/commit/04c393f3e77f53b3ff7c6e82199f9c5b2ac89c86

**Comment by GopherJ** [comment]
https://forum.polkadot.network/t/polkadot-kusama-bridge/2971/5

**Comment by acatangiu** [comment]
https://forum.polkadot.network/t/polkadot-kusama-bridge/2971/6

**Comment by acatangiu** [comment]
This is not "one bridge" - this repo holds building blocks for countless generic trustless bridges that can be configured to work with many types of chains.

There are already a number of live bridges in the ecosystem built using these components.

If you're referring to the Polkadot<>Kusama bridge in particular, then yes, its launch was rescheduled multiple times over the years as the networks themselves evolved. IMO, this was for the best, as now we'll have BridgeHub system parachains bridging any paras across universal consensuses; and we'll have an XCM bridge between Polkadot and Kusama with application-agnostic transport layer that is very flexible in what it allows. These things simply didn't exist 3 or 2 or even 1 years ago.

The title you chose for this issue comes off as cheap click-bait or flame-bait and I suggest you change it.
