### ISSUE TITLE
Stabilise storage format of Substrate Bridge Pallet

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#434]
After final release any storage changes will require migrations, so it's best to triple check that the storage format is final and does not prevent any future work that we might be doing later on.

Related: #371

**Comment by HCastano** [comment]
I think the related issue here should be  #371, not #369.

**Comment by svyatonik** [comment]
I'd say that the pallet-level structs, used by grandpa and messages pallet are quite stable. I was also (initially) thinking that we may use versioned enums for these, but it'll imo create additional problems acrually - i.e. we'll need to support versions at least in relayer and maybe checks in bridged pallet. Instead I'm suggesting to halt pallets and relayer until both chains are upgraded to the same version of the pallet.

AFAIK there's some kind of pallet version in the metadata, so we can add additional guard that will stop the relay if it sees unknown pallet version. But since pallet can only be updated with runtime, `spec_version` guard is enough for now (unless we fuck up with running wrong relay version).
