### ISSUE TITLE
Test how relay/apps behave when justifications are generated rarely

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#441]
Test how relay/apps will work when persistent justifications are generated rarely.
Tune/change other params (like `MaxUnconfirmedMessagesAtInboundLane`), to make sure it's able to handle the load.
Consider changing the session length of Millau - should be similar to Kusama/Polkadot;

**Comment by svyatonik** [comment]
I've changed session time in Millau to 5 minutes in #394 . So on Millau persistent justifications should be generated every 5 minutes starting from session 2. I can confirm that scheme #394 helps us to reduce finality time from ~5m to ~30s.

I can't test this on Polkadot/Kusama, unfortunately - don't have a synced client and can't sync now. But since: (1) we're going to use the same schema on these chains and (2) according to https://telemetry.polkadot.io/#/Polkadot and https://telemetry.polkadot.io/#list/Kusama all synced full nodes have the same finalized block (which is 2-4 blocks behind best block), then, I believe, we should not have large finality delays on Polkadot/Kusama as well.

So I'm closing the issue
