### ISSUE TITLE
Use `transaction_version` instead of `spec_version` when signing calls

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#538]
It seems that `RuntimeVersion.transaction_version` is supposed to change only when `Call`s are invalid.
We should confirm this and consider using it instead of `spec_version` in `Call::decode` dispatcher, since that would most likely require less manual work.

**Comment by svyatonik** [comment]
What if runtime method definition is changing? Iiuc (from [this document](https://github.com/paritytech/polkadot/blob/master/.github/ISSUE_TEMPLATE/release.md)) `transaction_version` is only incremented when pallet/extrinsic indices are changing (it may still left unchanged if we just append pallets/extrinsics). So it just cares about decoding pallet/extrinsic enums. But what if we have had `fn call(u64, u64)` that has changed to `fn call(u128)`? From what I understand, the `transaction_version` stays the same, but we should still reject this call, right? So probably better to rely on `spec_version` (like regular transactions do)? Or even verify both versions?

**Comment by tomusdrw** [comment]
That's a good question, indeed the document doesn't mention this case, but I was told that `transaction_version` has been crated for Hardware Wallets, so that they know how to interpret the call, which in theory should cater for such case.
Perhaps it's implicitly assumed that such breaking change should not happen at all?

Looking at the [docs](https://github.com/paritytech/substrate/blob/543891f9d97587d54aeda036ed0ee124748c6ca5/primitives/version/src/lib.rs#L98-L106) it seems it has a bit stronger guarantees than the release notes mention, perhaps we just need to update this?

CC @s3krit

**Comment by svyatonik** [comment]
> new calls don't necessitate a bump
> non-trivial type changes to existing calls do.
> (non-trivial == anything that would result in a pre-existing extrinsic being encoded differently)

So I believe you're right and tx version should be bumped in this case.

**Comment by svyatonik** [comment]
I'll leave my thoughts about this issue here, otherwise they'll be lost. I was looking at the #826 and spoiled messages are actually the worst thing from user perspective. Now every upgrade of Polkadot/Kusama chain means `spec_version` change => all messages undelivered to Polkadot/Kusama are spoiled after upgrade. So replacing `spec_version` with `transaction_version` seemed to be a good idea and easy to implement.

But then I've found that auto-updating weights is now a part of P/K release (e.g. https://github.com/paritytech/polkadot/pull/2497 and https://github.com/paritytech/polkadot/pull/2690). So weights are blindly updated with every runtime upgrade. What it means for us:
1) now we always fail to dispatch message that has been sent before upgrade with `MessageVersionSpecMismatch` error;
2) if we'll change to `transaction_version`, then we may either dispatch it or not, depending on the sender luck - if call weight has been decreased during upgrade (remember that weights are updated automatically. so they are always changing) then the message will be dispatched, if it was increased, then we'll fail with `MessageWeightMismatch`.

To me having clear in-advance understanding of whether your message will be dispatched or not is better than uncertainty. So I haven't opened PR for that.

Then I had an idea of introducing another halt-like call (or parameter) to the messages pallet that will just reject all new messages. It should be called by the pallet owner before (say when upgrade referendum is starting) target chain is upgraded. And then, when upgrade happens, resume must be called. This 'light halt' shall allow relayers to relay messages, but block all new messages from sending. But this approach has too many drawbacks: additional responsibility for us, large "light-halt" window, ... So I'd prefer to leave it to message senders (maybe warn in UI) - they must verify that there's no upgrade scheduled in near future + probably even run relay on their own if they see that messages are not being delivered.

The last thing to say is that if relays are always running, then we unlikely to see `MessageVersionSpecMismatch` too often - there aren't that many upgrades on real chains + messages must be sent exactly before upgrade happens to fail.

**Comment by tomusdrw** [comment]
> if we'll change to transaction_version, then we may either dispatch it or not, depending on the sender luck - if call weight has been decreased during upgrade (remember that weights are updated automatically. so they are always changing) then the message will be dispatched, if it was increased, then we'll fail with MessageWeightMismatch.

I'm not sure I fully understand the consequences cause I don't see the problem with this approach. Let me expand on how I understand this.

1. Users queueing up `Messages` to `OutboundLane` must pay the fees.
2. The fee structure includes:
    1. Cost of the source chain (storing the message)
    2. Cost of the delivery to target chain (weight for delivering the message converted to source tokens)
    3. Cost of dispatch on target chain (user-declared weight converted to source tokens)
    4. Cost of confirming the delivery back on the source chain (source chain weight to fee)
    5. Relayer tip (some fixed extra rate in source tokens)
3. There are only two things that deal with target-chain weights: `delivery` & `dispatch`
4. IMHO `dispatch` is irrelevant, cause it's generated by users.
    - There is a risk when users generate a message and the runtime upgrade happens in the meantime (after it's included) and because the declared user weight didn't have any buffer the message is now failing. But there are at least two strategies the user can take (we are assuming it's inspecting the target-chain status): (1) Add a buffer to the weight (i.e. overpay a bit - perhaps we can refund that instead of letting the relayer eat it?), (2) Delay the message / generate for new runtime in case it is in this short window of uncertainity.
    - On-chain components sending messages might have a more difficult task of accounting for that (no way to inspect the target chain), so these need to be a bit more careful and will probably need to overpay a bit)
5. `delivery` is relevant, but I think the source-runtime assumptions are already just an estimate, so we can add a safety buffer there.


I think this is pretty much solved by #561 (although might be a bit tricky for relayers), as a temporary solution perhaps we can change the version to be an enum instead:
```
enum ExpectedRuntimeVersion {
  SpecVersion(u32),
  TransactionVersion(u32),
}
```
So the user can decide what risk they are willing to take by specifying either spec-version to be matching or transaction-version (we can even add `ImplementationVersion`). What do you think?

**Comment by svyatonik** [comment]
I think that that for end-user perspective switching from `spec_version` to `transaction_version` looks like switching from statement#1 "we won't dispatch your message if runtime upgrade happens while it on the way" to statement#2 "we will dispatch your message even if upgrade happens, unless it changes tx version". But actually it is switch to statement#3 "we don't know if we'll be able to dispatch your message if upgrade happens, even if it doesn't change tx version", which to me seems worse than statement#1.

Adding extra weight is possible, indeed - I was going to suggest this for our UI when was thinking of this. Because weights may change even if `spec_version` doesn't change - it isn't a part of runtime specification iiuc. But adding extra cost (which cost btw?) to every message, even if there's no runtime scheduled is not wise. But if you need to look at the target chain to check if runtime upgrade is scheduled, then you may also estimate risks of having your message not dispatched. E.g. if upgrade referendum/intention/whatever takes a week and 6 days left, then you may just send the message without overpaying. If only a few hours left, then probably worth delaying your message until upgrade happens. And even if we switch to the `transaction_version` and few hours left and you're willing to overpay, then still it's in your interest to examine the new runtime and check whether transaction version matches. Otherwise, even if you overpay, the message won't be dispatched.

With on-chain senders the situation is similar - without watching either `transaction_version` or `spec_version` of the target chain, they are doomed. They will be acting like old blockchain clients that are running on an hard-forked blockchain + trying to update blockchain state.

Re your enum suggestion - imo it'll complicate things. E.g. a regular human will still be required to watch the target chain anyway if he's willing to make an informed decision between different options. The 'owner' or oracle of on-chain submitter must also do some actions - pause or upgrade pallet, probably adjust weights.

So as a conclusion: my opinion is that this upgrade right now won't make upgrade easier to both us and message senders. And it is the main thing why it needs to be introduced - to make it easier to survive upgrades.

**Comment by svyatonik** [comment]
irrelevant after #1376
