### ISSUE TITLE
Pay dispatch fee on the target chain.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#561]
Currently we pay dispatch fee on the source chain and that heavily relies on the price oracle (#540, #449) enforcing the minimal required fee.

To reduce that reliance we can consider paying the dispatch fee on the target chain. I think this should be an option though, cause it requires having some funds on the target account id, prior to any interactions.

The idea would be that on the source chain, you still pay for the delivery fee (includes the cost/weight of encoded call), but when we dispatch the call on the target chain we first try to pay the fee to the relayer's account and only dispatch if there is enough funds there.

Since the weight cost of dispatch would most likely be the largest of all other fees, this reduced the price oracle requirement.

This complicates the relayer strategy a bit and to make sure they don't really loose in case there is not enough funds on the target side to dispatch the call, the target fee the relayer pays should be reduced by unused (but declared) weight.
Hence the relayer should be profitable regardless of the fact if the target fee was payed or not, cause the source chain fee should always cover the delivery and the reward even in case of failed dispatch.

**Comment by svyatonik** [comment]
While working on this, I've found a problem with this approach. So I agree that when there's insufficient funds at the target chain to pay for the dispatch, we shall return funds to the relayer (that's why I was going to solve this issue and #377 in a single PR). But then the following scenario is possible:
1) sender wants to send message `{ encoded_call: vec![], dispatch_weight: MAX_WEIGHT }` and chooses to pay dispatch fee at the target chain;
2) at the source chain sender only pays for delivery and confirmation transactions. Cost of the first transaction then only depends on the message size. The cost of the second tx is fixed. And since we are delivering empty vec, the total cost isn't super-expensive;
3) when relayer submits delivery transaction, it declares its weight. And since the sender has declared it to be `MAX_WEIGHT`, we're blocking other transactions from being included into the block;
4) when trying to dispatch the call, we find that there's no funds at the dispatch origin account. We have two options here:
4.1) refund relayer, so that it won't lose anything. But then noone is actually paying for this `MAX_WEIGHT`. So we'll get almost-full blocks at the target chain without any utility. This: (a) blocks/slows down 'mining' of other transactions at the target chain and (b) increases `pallet_transaction_payment::Config::FeeMultiplierUpdate`, which makes transactions more expensive;
4.2) not to refund relayer. Then relayer will lose its own funds. A non-altruistic relayer would make a check before delivering this message and simply won't deliver it unless there are enough funds to pay for dispatch. So message like that would effectively block the lane.

There are couple of solutions, but they're far from ideal:
1) we may lock enough message sender funds at the source chain and if it has no funds at the target chain, transfer this amount to relayer account in confirmation transaction. This, however, won't lower our dependency on price oracle (this is the main reason why we're implementing this, right?);
2) we may ask to pay dispatch fee in advance. Then in `fn send_message()` we may ask for some proof-of-payment. This, however, has its own problems - e.g. what this proof is? It must be associated with the lane+nonce, but we get this pair only when message is accepted. What's the destination account for the fee - the sender can't pay directly to relayer, because there's no relayer at this point yet.

**Comment by tomusdrw** [comment]
> 4.1) refund relayer, so that it won't lose anything. But then noone is actually paying for this MAX_WEIGHT. So we'll get almost-full blocks at the target chain without any utility.

Actually, afair we can return the "unused weight" so the block will still be considered empty (i.e. we only charge weight up to the point where we figured the dispatch would fail). Similar to how in Ethereum there is a difference between declared gas limit and actual gas used.

If above is the case (and I'm 90% sure it is), then I don't see this an issue at all. The sender is overpaying such transaction anyway, so there is an obvious cost to this kind of attack that should prevent griefing validators or target chain blocks.

**Comment by svyatonik** [comment]
I'm not sure what you mean by "we can return the "unused weight"". Is it [this](https://github.com/paritytech/substrate/blob/982df173190685bb18b7ed46b860e36387b9a7a9/frame/support/src/weights.rs#L328)? But it is only available after block transactions have been selected. So what happens is that when we're preparing a block, we see that we can only fit single delivery tx, because it declares its weight = max available weight. So even if delivery call would return this `actual_weight` set to something near zero, all other transactions would have to wait. Or do you mean something else?

**Comment by tomusdrw** [comment]
> I'm not sure what you mean by "we can return the "unused weight"". Is it this?

Yes.

> So what happens is that when we're preparing a block, we see that we can only fit single delivery tx, because it declares its weight = max available weight. So even if delivery call would return this actual_weight set to something near zero, all other transactions would have to wait. Or do you mean something else?

Indeed. So the (griefing) attack you are describing would look like this:
1. The attacker sends a bunch of messages with `MAX_WEIGHT` declared.
2. Since `MAX_WEIGHT` is going to probably be quite close to maximal extrinsic on the target chain (minus the necessary envelope cost), the relayer is forced to split delivery of these messages into multiple delivery transactions (pretty much one message per transacton).
3. Now what block builders on the target chain have to do is: they see large transaction, but after applying it they see it didn't use up the entire weight (assuming we return), so they will attempt to push more transactions to the block (i.e. the blocks will not be under-utilised).
4. They can't however put other bridge transactions, cause they are quite large, so we end up with one-tx-per-block delivery. 

Note that following grief is completely valid even without the fees being payed on the target chain - the only difference is that currently the attacker has to pay the cost of the dispatch (assumption is that it's large chunk of the overall cost), while after this is implemented the costs for them are lower.
IMHO this requires a more through analysis, but my gut feeling is that it's not really a practical issue and there are couple of ideas how we could alleviate it if it becomes an issue listed here: https://github.com/paritytech/parity-bridges-common/issues/621 In particular I think of splitting delivery & dispatch or making the dispatch payload optional in case we see it would fail anyway.
Also some sort of mechanism for relayers to "bet" on transaction failure could work as well, i.e.:
1. The relayer simulates the dispatch and see it fails.
2. The relayer then delivers transaction and overrides the dispatch weight + puts additional deposit as a "bet"
3. If the bet get's challenged (by providing a proof of successful execution in that particular block) the relayer is slashed.

Obviously this stuff is not trivial to design and implement, but the bottom line is that there are possible solutions if this becomes an issue.
For the first version of the bridge I'd be more on an optimistic side though, and work on other safety mechanisms (like the ones you suggested) as a follow up. In the future particular lanes and relayers can choose their risk factor (and probably take it into account via fees) by allowing only safe messages (for instance pre-deposit on target chain).

**Comment by svyatonik** [comment]
> Note that following grief is completely valid even without the fees being payed on the target chain - the only difference is that currently the attacker has to pay the cost of the dispatch (assumption is that it's large chunk of the overall cost), while after this is implemented the costs for them are lower.

They are not simply lower, they are significantly lower. Like the basic weight of delivery transaction on Rialto is `1_000_000_000`. The max 'normal' extrinsic weight is `75% * 2_000_000_000_000 = 1_500_000_000_000`. So the malicious sender may send `1_500` messages to Rialto with `weight = MAX_WEIGHT` paying the same amount that he'll pay by submitting **single Rialto tx** with weight = `1_500_000_000_000` at the target chain. 

I don't agree that "it's not really a practical issue" - as I said above, sending simple `{ encoded_call: vec![], dispatch_weight: MAX_WEIGHT }` message will be accepted by the source runtime && if we'll fail to dispatch it at the target chain, then either relayer is paying for the dispatch, or noone is paying for that. Both options are unacceptable.

> or making the dispatch payload optional in case we see it would fail anyway.

This may help, but checking transaction on state `A` doesn't mean that it'll be executed at state `A`. Like relayer may see that the origin has enough funds, submits a delivery tx, then origin sees this transaction and submits another one (with higher tip) to withdraw funds => relayer would lose it. Also, since we can't even be sure whether call will succeed in next block or not.

**Comment by svyatonik** [comment]
We had a chat about my last comment in other thread && actually I've been wrong about how weight refund works in Substrate/Polkadot. My assumption was that post-dispatch info is only used to refund **tx fee** to the origin. But it is actually used when block is being built. So if pre-dispatch declares weight=100 and post-dispatch returns 90, then these 10 units are "returned" to the pool and may be used by next transactions. Because of this we may return unused weight to relayer and it won't block 'mining' other transactions.
