### ISSUE TITLE
Prune old headers with separate transaction

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#62]
And potentially reward submitter for pruning (if prune transaction is signed? or should we only accept signed pruning transactions?)

**PART 1: Problem with unsigned transactions**
1) authority generates multiple valid headers at its slot;
2) (most of) headers are 'mined' and occupy storage;
3) we have potentially unlimited number of entries in the [`HeadersByNumber`](https://github.com/paritytech/parity-bridges-common/blob/878d17a3ec99fe0776d926873242de2807818f63/modules/ethereum/src/lib.rs#L364) map;
4) later, when one of these headers is finalized, we may end up exceeding block (weight? fee?) limit because we need to prune these headers [here](https://github.com/paritytech/parity-bridges-common/blob/878d17a3ec99fe0776d926873242de2807818f63/modules/ethereum/src/lib.rs#L589) => transaction with **valid header** submitted by **good validator** is not accepted => the sync is stuck.

**PART 2: Problem with signed transactions**
The problem is the same, though malicious authority will pay for its actions. But the sync will stuck anyway.

**PART 3: Potential solution**
Do not intermix headers sync with headers pruning - there should be another API entry for pruning obsolete headers. Probably we need to reward for calling this method?

Another solution would be to disable pruning at all.

**Comment by tomusdrw** [comment]
Weights do not depend on storage size currently. I think we only support fixed-size weights, so probably because of this we probably won't run into that issue.
However this is not really a solution, and the problem might still be there when we introduce more sophisticated weighting mechanism. I like the idea of splitting pruning, but would prefer to have that configurable. I.e. in some chains where we can safely limit the number of forks, we could perform pruning anyway. We could also perform pruning if the number of forks is within limits.
