### ISSUE TITLE
Relay Proofs to Finality Verifier Pallet

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#703]
Since the Finality Verifier pallet has now been added to the Millau and Rialto runtimes
we should start testing that it actually works by writing some relayer code that calls
the [`pallet_finality_verifier::submit_finality_proof()`](https://github.com/paritytech/parity-bridges-common/blob/master/modules/finality-verifier/src/lib.rs#L99)
extrinsic. To do this we need three things: a header, justification, and finality proof.

We already subscribe to justifications using the `grandpa_subscribeJustifications` RPC
[here](https://github.com/paritytech/parity-bridges-common/blob/master/relays/substrate-client/src/client.rs#L259). The stream of justifications are used in the
[`headers_maintain`](https://github.com/paritytech/parity-bridges-common/blob/master/relays/substrate/src/headers_maintain.rs) pipeline. We can probably leverage some similar code to get the 
`finality_target` and `justification` required by `pallet-finality-verifier`.

As for the ancestry proof, we keep a few queues of the headers
[here](https://github.com/paritytech/parity-bridges-common/blob/master/relays/headers-relay/src/headers.rs). I think we can add a queue to keep track of the headers between
`[last_finalized, finality_target]`.

With this in hand I think what we need to do next is add a method to
[`SubstrateHeaderSyncPipeline`](https://github.com/paritytech/parity-bridges-common/blob/master/relays/substrate/src/headers_pipeline.rs#L36) that actually generates a transaction with a call to
`submit_finality_proof()`.

Since @svyatonik is the expert when it comes to the relayer code, do you think this
sounds reasonable, or are there other places in the code that need to be updated to
accomodate this?

**Comment by svyatonik** [comment]
I suggest first to finish up pallet API - right now I have no idea on what would it look like when relay starts with, say, 10_000 missed headers. They couldn't fit in single tx, obviously. What shall relayer do then? Submit some "hold-on-i-m-going-to-submit-10000-headers" transaction? What if other "reserve" is active (i.e. other relayer is submitting 10000 transactions)? What if other relayer that has "reserved" slot isn't submitting anything - who's responsible for determining that?

I think this whole scheme may significantly affect relayer implementation && should at least be designed before work on relayer is started.

**Comment by HCastano** [comment]
Yeah, that's a good point Slava.

After talking with Tomek, Andre, and Andreas today we had some ideas for a scheme in
which the Finality Verifier didn't need to support this multi-stage protocol when
importing a large number of missed headers. I (or maybe Tomek, depending on the timing)
will write out more details about this in #628.

As such, the relayer will "just" need to support the standard API that's being exposed
now (so header, justification, and ancestry proof). The ancestry proof format is a little
in the air at the moment, but I hope we can at least start implementing some relayer code
soon.

**Comment by svyatonik** [comment]
> we can at least start implementing some relayer code soon.

Ok, let's just please stabilize pallet API first :) There are already 2.5 different approaches in #628 and e.g. transfer from 1st to 2nd would have completely changed the way relayer is implemented.

**Comment by tomusdrw** [comment]
@svyatonik added description in #628. The workflow will always be the same:
1. Listen to finality notifications from GRANDPA (`new_finalized`)
2. For every notification check the target chain and get on-chain best block. (`prev_finalized`)
3. Prepare ancestry proof between `[new_finalized, prev_finalized]`.

The implementation of the last step will change - with current pallet we need full header-chain, later on it will be the storage proof and long term MMR proof.

Do you see any caveats in such approach? Perhaps I'm missing something obvious here.

**Comment by svyatonik** [comment]
Yes - I'm still having the same concerns. What if we can't fit `Chain(Vec<Header>)` in single transaction because of weights? Say we have missed session, then we'll need roughly `session_length_in_hours * blocks_per_hour` hashes + same number of db write ops. I don't know what's session length on polkadot/kusama, but googling shows that it's 4hrs (that's definitely the slot that we can miss && I don't think we're ok with manually rebasing bridge to new header every time). So with block time = 4 * 60 * 60 / 5 = 2880 headers (I'm not sure if this number can grow, but I guess it can when GRANDPA is lagging). So it'll be >= 2880 `BlakeTwo256` calls and (if we're going to write headers) 2880 write operations. This doesn't include other operations - db reads, signatures verification, ...

I imagine that such transaction may not fit the polkadot/kusama block. But I can't prove that, since there's no any benchmarks yet. So what I'm suggesting here, is to avoid implementing anything in relay, until we'll be sure that this ^^^ isn't an issue.
