### ISSUE TITLE
What's the function of shift session manager

### ISSUE THREAD

**Issue by fewensa** [paritytech/parity-bridges-common#970]
Hi

https://github.com/paritytech/parity-bridges-common/blob/0e767b3af78aea25e74f8bad7cb6152eb5f6c5b7/bin/millau/runtime/src/lib.rs#L339

https://github.com/paritytech/parity-bridges-common/blob/0e767b3af78aea25e74f8bad7cb6152eb5f6c5b7/bin/millau/runtime/src/lib.rs#L406

the `pallet-shift-session-manager` is added to Millau and Rialto node, but I did not find any place to call this pallet.

I saw this description

https://github.com/paritytech/parity-bridges-common/blob/0e767b3af78aea25e74f8bad7cb6152eb5f6c5b7/modules/shift-session-manager/Cargo.toml#L3

Because I haven't seen any place to call this pallet, I want to confirm what it does

**Comment by svyatonik** [comment]
It's used by both [Rialto runtime](https://github.com/paritytech/parity-bridges-common/blob/master/bin/rialto/runtime/src/lib.rs#L403) and [Millau runtime](https://github.com/paritytech/parity-bridges-common/blob/master/bin/millau/runtime/src/lib.rs#L297). It is called by session manager to select valdators for new session. And what it does is simply selecting new validators set (of 2/3 initial validators) for every session.

**Comment by AsceticBear** [comment]
@svyatonik Thanks for your reply. I am confused about this pallet and try to figure out the following question:

1. Is `pallet_shift_session_manager` is a must pallet for chains who want to use the s2s bridge?
2. For running chain node which has config like [Crab Network Session Manager Setting](https://github.com/darwinia-network/darwinia/blob/master/runtime/crab/src/pallets/session.rs#L26), in order to integrate with S2S bridge, should we update the `SessionManager` from `NoteHistoricalRoot<Self, Staking>` to `pallet_shift_session_manager::Pallet<Runtime>`?

**Comment by svyatonik** [comment]
No - we're just using it in our test chains as an easy way to have different authorities set at every session (to test how our GRANDPA module works with such sessions). You're free to use any other session manger in your chains - there are no any requirements about that
